spring:
  profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root$2025
    url: jdbc:mysql://localhost:3306/ET3

    #    url: jdbc:mysql://localhost:3306/ET3
#    url:jdbc:mysql://host.docker.internal:3306/ET3
    username: root
  jpa:
    hibernate:
      ddl-auto: update
welcome:
  message: Welcome to spring world in dev
#spring:
#  profiles: dev
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://db:3306/ET3
#    username: root
#    password: root$2025
#  jpa:
#    hibernate:
#      ddl-auto: update
#welcome:
#  message: Welcome to spring world in dev



#spring:
#  config:
#    activate:
#      on-profile: dev
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/ET3
#    username: root
#    password: root$2025
#  jpa:
#    hibernate:
#      ddl-auto: update
#welcome:
#  message: Welcome to spring world in dev
